# Generated by Django 5.2.5 on 2025-08-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='publications',
            field=models.ManyToManyField(blank=True, related_name='collections', through='base.CollectionPublication', to='base.publication'),
        ),
    ]
