# Generated by Django 5.2.5 on 2025-08-18 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_collection_publications'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('follow', 'New Follower'), ('publication_like', 'Publication Liked'), ('publication_comment', 'New Comment on Publication'), ('collection_shared', 'Collection Shared'), ('discussion_reply', 'Discussion Reply'), ('discussion_mention', 'Mentioned in Discussion'), ('publication_added', 'New Publication from Followed User'), ('topic_follow', 'Someone Followed Your Topic'), ('system', 'System Notification'), ('achievement', 'Achievement Unlocked')], max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['recipient', '-created'], name='base_notifi_recipie_a28bbc_idx'), models.Index(fields=['recipient', 'is_read'], name='base_notifi_recipie_f4002f_idx')],
            },
        ),
    ]
