# Generated by Django 5.2.5 on 2025-08-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_discussion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'New Follower'), ('discussion_in_publication', 'New discussion in publication'), ('publication_like', 'Publication Liked'), ('publication_comment', 'New Comment on Publication'), ('collection_shared', 'Collection Shared'), ('discussion_reply', 'Discussion Reply'), ('discussion_mention', 'Mentioned in Discussion'), ('publication_added', 'New Publication from Followed User'), ('topic_follow', 'Someone Followed Your Topic'), ('system', 'System Notification'), ('achievement', 'Achievement Unlocked')], max_length=50),
        ),
    ]
