# Generated by Django 5.2.5 on 2025-08-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='publication',
        ),
        migrations.AddField(
            model_name='message',
            name='discussion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.discussion'),
            preserve_default=False,
        ),
    ]
