# Generated by Django 5.2.5 on 2025-08-26 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_message_reply_to'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True)),
                ('search_count', models.PositiveIntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-search_count', '-last_searched'],
                'indexes': [models.Index(fields=['query'], name='base_search_query_cc259e_idx'), models.Index(fields=['-search_count'], name='base_search_search__09f317_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('search_type', models.CharField(choices=[('general', 'General Search'), ('publication', 'Publication Search'), ('author', 'Author Search'), ('collection', 'Collection Search'), ('profile', 'Profile Search'), ('discussion', 'Discussion Search'), ('tag', 'Tag Search')], default='general', max_length=50)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('usage_count', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search histories',
                'ordering': ['-last_used'],
                'indexes': [models.Index(fields=['user', '-last_used'], name='base_search_user_id_8120b0_idx'), models.Index(fields=['user', 'query'], name='base_search_user_id_bf719e_idx')],
                'unique_together': {('user', 'query', 'search_type')},
            },
        ),
    ]
