# Generated by Django 5.2.5 on 2025-08-26 11:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_searchsuggestion_searchhistory'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together={('user', 'query', 'search_type', 'content_type', 'object_id')},
        ),
    ]
