# Generated by Django 5.2.5 on 2025-08-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_searchhistory_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='base_search_user_id_bf719e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together=set(),
        ),
    ]
